pub const CLOCK_FREQ: usize = 12500000;
pub const USER_STACK_SIZE: usize = 4096 * 2;
pub const KERNEL_STACK_SIZE: usize = 4096 * 2;
pub const KERNEL_HEAP_SIZE: usize = 4096 * 16;
pub const PAGE_SIZE: usize = 1 << PAGE_SIZE_BITS;
pub const PAGE_SIZE_BITS: usize = 12;
pub const MEMORY_END: usize = 0x80800000;
pub const TRAMPOLINE: usize = usize::MAX - PAGE_SIZE + 1;
pub const TRAP_CONTEXT: usize = TRAMPOLINE - PAGE_SIZE;
